import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Footer from "./-componants/footer/footer";
import Navbar from "./-componants/navbar/navbar";
import Firstnav from "./-componants/fiestnav/firstnav";
import { Toaster } from "@/components/ui/toast";
import Myprovider from "./-componants/myprovider/myprovider";
import Providers from "./tanstackprovider/tanstackprovider";
const Exofont = Exo({
  variable: "--font-Exo",
  weight: ['100', '400', '700']
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`   antialiased`}
    >
      <body className="">
        <Providers>
          <Myprovider>

            <Firstnav />
            <Navbar />
            <div className="container mx-auto xl:max-w-7xl">

              {children}
              <Toaster />

            </div>
            <Footer />
          </Myprovider>
        </Providers>
      </body >
    </html >
  );
}
